spring.application.name=globalhub-api

spring.docker.compose.enabled=false

spring.datasource.url=jdbc:postgresql://localhost:5435/globalhub-db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

api.security.token.secret=meu-segredo-super-secreto-123

logging.level.org.springframework.security=DEBUG

globalhub.admin.email=${ADMIN_EMAIL:suporte@globalhub.com}
globalhub.admin.password=${ADMIN_PASSWORD:SenhaSuperForte123!}